# Generated by Django 6.1 on 2026-08-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
